"""Verify script for generate-section-draft-references — generated by
script/schema/generate_per_domain_usecases.py (pcems_2026), do not hand-edit.

References collation: fan-in usecase that builds the references draft
from all other domains' citations."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent.parent.parent / "common" / "script"))
from _common import verify_main

if __name__ == "__main__":
    verify_main("generate-section-draft-references")
