"""Verify script for section-citations-references — generated by
script/schema/generate_per_domain_usecases.py (pcems_2026), do not hand-edit.

References collation fan-in: validates cross-references between
citations and reference list."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent.parent.parent / "common" / "script"))
from _common import verify_main

if __name__ == "__main__":
    verify_main("section-citations-references")
