#!/usr/bin/env python3
"""
generate_per_domain_usecases.py — pcems_2026's per-domain verify script
generator (originally adapted from base_academic's own generator, now
fully self-contained). Produces:

  script/verify/uc{...}_{domain}.py  — thin wrappers around
                                       script/verify/_common.py (local)

Does NOT regenerate plan/usecase/*.md (hand-written for pcems_2026) or
standard.yaml's usecases: block (already correct). Only generates the
verify scripts for pcems_2026's own domain list (especially 'findings',
which base_academic's generic domain set doesn't have).

Run from pcems_2026 root:
  python script/schema/generate_per_domain_usecases.py
"""
from pathlib import Path

# pcems_2026 root = script/schema/ -> ../../
PCEMS_ROOT = Path(__file__).resolve().parent.parent.parent

STRUCTURAL_DOMAINS = [
    "title-and-metadata", "introduction", "methodology",
    "findings", "conclusion", "references",
]
GENERATED_DOMAINS = [d for d in STRUCTURAL_DOMAINS if d != "references"]


def snake(domain):
    return domain.replace("-", "_")


def write(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


VERIFY_TEMPLATE = '''"""Verify script for {usecase_name} — generated by
script/schema/generate_per_domain_usecases.py (pcems_2026), do not hand-edit;
edit that generator and re-run instead.

Delegates to _common.py in this same directory."""
import sys
from pathlib import Path

# _common.py lives in this same directory
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import verify_main

if __name__ == "__main__":
    verify_main("{usecase_name}")
'''


def gen_verify(filename, usecase_name):
    write(PCEMS_ROOT / "script" / "verify" / filename,
          VERIFY_TEMPLATE.format(usecase_name=usecase_name))
    print(f"  {filename}")


def main():
    print("generating pcems_2026 verify scripts...")
    count = 0

    # --- 4a: generate-section-draft-{domain} ---
    for d in GENERATED_DOMAINS:
        name = f"generate-section-draft-{d}"
        gen_verify(f"uc4a_generate_{snake(d)}.py", name)
        count += 1

    # --- 4b: section-citations-{domain} ---
    for d in GENERATED_DOMAINS:
        name = f"section-citations-{d}"
        gen_verify(f"uc4b_cite_{snake(d)}.py", name)
        count += 1

    # --- 4b: section-citations-references (fan-in) ---
    gen_verify("uc4b_collate_references.py", "section-citations-references")
    count += 1

    # --- 4c: section-enrichment-{domain} ---
    for d in STRUCTURAL_DOMAINS:
        name = f"section-enrichment-{d}"
        gen_verify(f"uc4c_enrich_{snake(d)}.py", name)
        count += 1

    # --- 4d: section-budget-fit-{domain} ---
    for d in STRUCTURAL_DOMAINS:
        name = f"section-budget-fit-{d}"
        gen_verify(f"uc4d_budget_{snake(d)}.py", name)
        count += 1

    # --- 4d: section-budget-fit-total (fan-in) ---
    gen_verify("uc4d_budget_total.py", "section-budget-fit-total")
    count += 1

    # --- 5: deterministic-audit-{domain} ---
    for d in STRUCTURAL_DOMAINS:
        name = f"deterministic-audit-{d}"
        gen_verify(f"uc5_audit_det_{snake(d)}.py", name)
        count += 1

    # --- 5a: semantic-audit-{domain} ---
    for d in STRUCTURAL_DOMAINS:
        name = f"semantic-audit-{d}"
        gen_verify(f"uc5a_audit_sem_{snake(d)}.py", name)
        count += 1

    # --- 5b: plagiarism-forensic-audit-{domain} ---
    for d in STRUCTURAL_DOMAINS:
        name = f"plagiarism-forensic-audit-{d}"
        gen_verify(f"uc5b_plagiarism_{snake(d)}.py", name)
        count += 1

    # --- 5c: humanize-deterministic-{domain} ---
    for d in STRUCTURAL_DOMAINS:
        name = f"humanize-deterministic-{d}"
        gen_verify(f"uc5c_humanize_det_{snake(d)}.py", name)
        count += 1

    # --- 5d: humanize-semantic-{domain} ---
    for d in STRUCTURAL_DOMAINS:
        name = f"humanize-semantic-{d}"
        gen_verify(f"uc5d_humanize_sem_{snake(d)}.py", name)
        count += 1

    print(f"\ngenerated {count} verify scripts in {PCEMS_ROOT / 'script' / 'verify'}")


if __name__ == "__main__":
    main()
