-- knowledge.db — one row per chart PNG actually generated by
-- render_charts.py, recorded via common/hackathon_schema.py's
-- record_visualization(). team_id/domain_id are NULL where the chart's own
-- scope doesn't need them (see 10-hackathon_visualization_types.sql) — e.g.
-- domain_weights has both NULL, rank_distribution has domain_id only,
-- team_radar has team_id only. A report step calls get_visualization()
-- before re-rendering a chart it may already have — backtrace, not
-- regenerate.

CREATE TABLE IF NOT EXISTS hackathon_visualizations (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    chart_type_id INTEGER NOT NULL REFERENCES hackathon_visualization_types(id) ON DELETE CASCADE,
    team_id       INTEGER REFERENCES hackathon_teams(id) ON DELETE CASCADE,
    domain_id     INTEGER REFERENCES hackathon_domains(id) ON DELETE CASCADE,
    file_path     TEXT    NOT NULL,
    created_at    TEXT    NOT NULL
);
