"""Verify script for plagiarism-forensic-audit-limitations — generated by
script/schema/generate_per_domain_usecases.py, do not hand-edit; edit that
generator and re-run instead."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import verify_main

if __name__ == "__main__":
    verify_main("plagiarism-forensic-audit-limitations")
