#!/usr/bin/env python3
"""Generate the Dharma Section Maps and Section Profiles for rust_dev.

Projects the rust_dev standard's per-section deterministic audit rules
(``samgraha/system/dev/rust_dev/common/tier*/audit/deterministic/section/``)
into Dharma's Domain System layout
(``dharma/domain/system/dev/rust_dev/domain/``):

  domain/map/<domain>-map.yaml          one Section Map per domain (13)
  domain/profile/<domain>/<section>.yaml  one Section Profile per audit file (136)

Rules encoded here (per docs/proposal/00-rust_dev-dharma-domain-system-proposal.md,
sections 4-5):

* One map ``sections[]`` entry per audit file, in the file's numeric (NN-)
  order. ``required`` comes from the audit rule whose ``evidence.type`` is
  ``section_presence`` (its ``mandatory`` value); a file with no such rule is
  template-conformance-only and is ``required: false``. A file with no
  matching section in the domain markdown is an orphan and is emitted with
  ``generated: true`` (2 such files exist, both in architecture).
* Each section's ``profile`` key equals the audit file's own snake_case key
  verbatim (never re-cased), and the profile file is named from that same key.
* Each profile's ``validation.rules`` carries the audit rules through
  field-for-field (id/description/condition/message/severity/weight/mandatory/
  evidence). ``writing_objective`` is composed from the section's Writing
  Guidance when one exists; otherwise (and for knowledge_goal/reader_goal
  always) an explicitly-marked authored placeholder is emitted, since no
  source exists in the standard for those fields.
* No shared profile-default file is produced.

The standard tree under ``samgraha/system/dev/rust_dev`` is read-only input.
Rerun this script at any time to regenerate the projection.
"""

import argparse
import os
import re
import sys
from collections import OrderedDict

import yaml

PROPOSAL = "docs/proposal/00-rust_dev-dharma-domain-system-proposal.md"
MAP_VERSION = "0.1.0"
AUTHORED_PLACEHOLDER = (
    "Authored placeholder - no source exists in the rust_dev standard for this "
    "field; generated by " + os.path.basename(__file__) + " until a human "
    "author writes it."
)


class BlockDumper(yaml.SafeDumper):
    pass


def _str_representer(dumper, data):
    style = None
    if len(data) > 60 and "\n" not in data and data.strip() and not data[0].isspace():
        style = ">"
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)


BlockDumper.add_representer(str, _str_representer)


def _odict_representer(dumper, data):
    return dumper.represent_dict(data.items())


BlockDumper.add_representer(OrderedDict, _odict_representer)


def dump_yaml(obj):
    return yaml.dump(
        obj, Dumper=BlockDumper, default_flow_style=False, sort_keys=False, allow_unicode=True, width=80
    )


def section_key(filename):
    """NN-<section>.yaml -> <section> (the snake_case key, verbatim)."""
    base = os.path.basename(filename)
    base = re.sub(r"^\d+-", "", base)
    return base.replace(".yaml", "")


def natural_order(filename):
    m = re.match(r"^(\d+)-", os.path.basename(filename))
    return int(m.group(1)) if m else 0


def title_case(key):
    return " ".join(word[0].upper() + word[1:] if word else word for word in key.split("_"))


def load_audit_corpus(src_root):
    """Return {domain: [OrderedDict(path=..., data=..., key=..., order=...)]}."""
    audit_dir = os.path.join(src_root, "common")
    corpus = {}
    for dirpath, _dirs, files in os.walk(audit_dir):
        tail = os.path.relpath(dirpath, audit_dir)
        parts = tail.split(os.sep)
        # .../tier{N}/audit/deterministic/section/<domain>
        if len(parts) == 5 and parts[3] == "section":
            domain = parts[4]
            for fname in sorted(files, key=natural_order):
                if not fname.endswith(".yaml"):
                    continue
                path = os.path.join(dirpath, fname)
                with open(path, encoding="utf-8-sig") as fh:
                    data = yaml.safe_load(fh)
                rel = os.path.join("common", *parts, fname).replace(os.sep, "/")
                corpus.setdefault(domain, []).append(
                    OrderedDict(path=path, rel=rel, data=data or {}, key=section_key(fname), order=natural_order(fname))
                )
    return corpus


def parse_domain_md(md_path):
    """Return {section_key: block} plus metadata for one domain markdown file."""
    with open(md_path, encoding="utf-8-sig") as fh:
        text = fh.read()
    sections = re.split(r"\n(?=## [^#])", text)
    result = OrderedDict()
    structural_pat = re.compile(r"Structural rules:\s*`([^`]+?)`")
    for block in sections:
        m = structural_pat.search(block)
        if not m:
            continue
        key = section_key(m.group(1))
        heading_m = re.match(r"## (.+)", block)
        result[key] = {
            "title": heading_m.group(1).strip() if heading_m else title_case(key),
            "block": block,
            "ref": m.group(1).strip(),
        }
    return result


def template_fields(block):
    fields = {}
    for m in re.finditer(r"> \*\*([^*]+):\*\*\s*([^\n]+)", block):
        fields[m.group(1).strip()] = m.group(2).strip()
    for m in re.finditer(r"\*\*(Required|Optional) (subsections|diagrams|cross-references):\*\*\s*([^\n]+)", block):
        fields[f"{m.group(1).lower()}_{m.group(2)}"] = m.group(3).strip()
    return fields


def writing_guidance(block):
    wg = {}
    wm = re.search(r"### Writing Guidance\n(.*?)(?=\n---\n|\n## [^#]|\Z)", block, re.S)
    if not wm:
        return wg
    for line in wm.group(1).splitlines():
        m = re.match(r"\s*-\s+\*\*([^*]+):\*\*\s*(.*)$", line)
        if m:
            wg[m.group(1).strip()] = m.group(2).strip()
    return wg


def section_required(rule_list):
    for rule in rule_list or []:
        ev = (rule or {}).get("evidence") or {}
        if ev.get("type") == "section_presence":
            return bool(rule.get("mandatory"))
    return False


def structural_evidence(rule_list):
    out = OrderedDict()
    for rule in rule_list or []:
        ev = (rule or {}).get("evidence") or {}
        if ev.get("type") != "structural_check":
            continue
        for k in ("min_paragraphs", "min_lists", "min_items", "required_subsections", "required_diagrams"):
            if k in ev and k not in out:
                out[k] = ev[k]
    return out


def compose_writing_objective(title, wg):
    parts = [f"Write the {title} section"]
    if wg.get("Voice"):
        parts.append(f"in the {wg['Voice']} voice")
    if wg.get("Structure"):
        parts.append(f"in {wg['Structure']} form")
    if wg.get("Tone"):
        article = "an" if wg["Tone"][:1].lower() in "aeiou" else "a"
        parts.append(f"with {article} {wg['Tone']} tone")
    if wg.get("Audience"):
        parts.append(f"for the {wg['Audience']}")
    head = ", ".join(parts) + "."
    body = []
    if wg.get("Do"):
        body.append("Do: " + wg["Do"] + ".")
    if wg.get("Don't"):
        body.append("Don't: " + wg["Don't"] + ".")
    return " ".join([head] + body)


def build_domain_map(domain, entries, md_sections, src_root):
    md_has = {k: v for k, v in md_sections.items() if "### Template" in v["block"]}
    template_count = len(md_has)
    orphan_keys = [e["key"] for e in entries if e["key"] not in md_sections]
    if template_count + len(orphan_keys) != len(entries):
        raise SystemExit(
            f"[preflight] {domain}: Template blocks {template_count} + orphans "
            f"{len(orphan_keys)} != audit files {len(entries)}. Refusing to emit."
        )
    sections = []
    for entry in entries:
        key = entry["key"]
        md = md_sections.get(key)
        is_orphan = md is None
        required = section_required(entry["data"].get("rules"))
        n_rules = len(entry["data"].get("rules") or [])
        if is_orphan:
            title = title_case(key)
            purpose = (
                f"{title} section of the {domain.title()} document - generated "
                f"(no authored template section exists in the standard); "
                f"{n_rules} deterministic audit rule(s) govern validation "
                f"(source: {entry['rel']})."
            )
        else:
            title = md["title"]
            flag = "Required" if required else "Optional"
            purpose = (
                f"{title} section of the {domain.title()} document. {flag}; "
                f"{n_rules} deterministic audit rule(s) govern validation "
                f"(source: {entry['rel']})."
            )
        sections.append(
            OrderedDict(
                id=key,
                title=title,
                parent_id="root",
                level=1,
                order=entry["order"],
                required=required,
                generated=is_orphan,
                source=entry["rel"],
                profile=key,
                purpose=purpose,
            )
        )
    return OrderedDict(
        schema=OrderedDict(
            id=f"rust_dev.dharma.domain.{domain}-map",
            name=f"{domain.title()} Section Map",
            version=MAP_VERSION,
        ),
        description=(
            f"Section map for the {domain} document domain of the rust-dev-domain "
            f"Dharma Domain System, generated from the rust_dev standard's "
            f"per-section deterministic audit rules "
            f"(samgraha/system/dev/rust_dev/common/tier*/audit/deterministic/section/{domain}/)."
        ),
        sections=sections,
        validation=OrderedDict(
            hierarchy=OrderedDict(max_level=1, require_valid_parent=True, root_parent_id="root"),
            ordering=OrderedDict(unique_order_per_parent=True),
            structure=OrderedDict(
                duplicate_ids=False,
                orphan_sections=bool(orphan_keys),
                circular_references=False,
            ),
            required=OrderedDict(enforce_required_sections=True, enforce_required_subsections=True),
        ),
    )


def build_profile(domain, entry, md, src_root):
    data = entry["data"]
    rules = data.get("rules") or []
    key = entry["key"]
    n_rules = len(rules)
    struct = structural_evidence(rules)
    if md is None:
        title = title_case(key)
        domain_file = f"domain/{find_domain_md(src_root, domain)}"
        objective = (
            f"Authored/minimal by construction - no {domain} template section "
            f"exists in {domain_file}; this section is generated and its "
            f"profile is validation-only ({n_rules} deterministic audit "
            f"rule(s), see validation.rules)."
        )
    else:
        title = md["title"]
        wg = writing_guidance(md["block"])
        if wg:
            objective = compose_writing_objective(title, wg)
        else:
            objective = (
                "Authored placeholder - the rust_dev standard's "
                f"{md['ref']} carries no Writing Guidance for this section; "
                f"objective pending human author. Section behavior is defined "
                f"by its {n_rules} deterministic audit rule(s) "
                "(see validation.rules)."
            )

    fields = template_fields(md["block"]) if md else {}

    def split_list(value):
        if not value or value.lower() in ("none", "n/a", ""):
            return []
        return [v.strip() for v in re.split(r",|;| and ", value) if v.strip()]

    required_inputs = split_list(fields.get("required_cross-references"))
    expected = []
    for k in ("required_subsections", "required_diagrams"):
        if fields.get(k) and fields[k].lower() not in ("none", ""):
            expected.append(fields[k])
    if "min_paragraphs" in struct:
        expected.append(f"at least {struct['min_paragraphs']} paragraph(s)")
    if "min_lists" in struct:
        expected.append(f"at least {struct['min_lists']} list(s)")
    if "min_items" in struct:
        expected.append(f"at least {struct['min_items']} item(s)")
    if struct.get("required_subsections"):
        expected.append("subsections: " + ", ".join(struct["required_subsections"]))

    if md is None:
        objective_text = (
            "Authored/minimal by construction - no authored {0} section exists "
            "to derive a {1} from; pending human author."
        )
        knowledge = objective_text.format(domain, "knowledge goal")
        reader = objective_text.format(domain, "reader goal")
    else:
        knowledge = AUTHORED_PLACEHOLDER
        reader = AUTHORED_PLACEHOLDER

    return OrderedDict(
        schema=OrderedDict(
            id=f"rust_dev.dharma.domain.{domain}.profile.{key}",
            name=f"{title} Section Profile",
            version=MAP_VERSION,
        ),
        source=entry["rel"],
        section=OrderedDict(
            id=key,
            writing_objective=objective,
            knowledge_goal=knowledge,
            reader_goal=reader,
            required_inputs=required_inputs,
            expected_outputs=OrderedDict(primary=expected),
            subsections=OrderedDict(),
            completion=OrderedDict(checklist=[r.get("description", "") for r in rules]),
            review=OrderedDict(questions=[]),
            validation=OrderedDict(rules=rules),
        ),
    )


def find_domain_md(src_root, domain):
    domain_dir = os.path.join(src_root, "domain")
    for fname in sorted(os.listdir(domain_dir)):
        if fname.endswith(".md") and re.sub(r"^\d+-", "", fname).replace(".md", "") == domain:
            return fname
    return None


def find_repo_root():
    cur = os.path.dirname(os.path.abspath(__file__))
    while os.path.dirname(cur) != cur:
        if os.path.isdir(os.path.join(cur, "samgraha", "system", "dev", "rust_dev")):
            return cur
        cur = os.path.dirname(cur)
    raise SystemExit("could not locate Kriti repo root (samgraha/system/dev/rust_dev) above this script")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    repo_root = find_repo_root()
    parser.add_argument("--src", default=os.path.join(repo_root, "samgraha", "system", "dev", "rust_dev"))
    parser.add_argument("--out", default=os.path.join(repo_root, "dharma", "domain", "system", "dev", "rust_dev"))
    args = parser.parse_args()
    src_root = os.path.abspath(args.src)
    out_root = os.path.abspath(args.out)

    corpus = load_audit_corpus(src_root)
    total_audit = sum(len(v) for v in corpus.values())
    print(f"audit files found: {total_audit} across {len(corpus)} domains")

    domain_dir = os.path.join(src_root, "domain")
    md_names = sorted(f for f in os.listdir(domain_dir) if f.endswith(".md"))
    md_by_domain = {}
    for fname in md_names:
        dom = re.sub(r"^\d+-", "", fname).replace(".md", "")
        md_by_domain[dom] = os.path.join(domain_dir, fname)

    missing = set(md_by_domain) - set(corpus)
    if missing:
        raise SystemExit(f"[preflight] domains with markdown but no audit folder: {sorted(missing)}")

    map_dir = os.path.join(out_root, "domain", "map")
    profile_dir = os.path.join(out_root, "domain", "profile")
    os.makedirs(map_dir, exist_ok=True)

    n_maps = n_profiles = 0
    for domain in sorted(md_by_domain):
        entries = corpus[domain]
        md_sections = parse_domain_md(md_by_domain[domain])
        map_doc = build_domain_map(domain, entries, md_sections, src_root)
        map_path = os.path.join(map_dir, f"{domain}-map.yaml")
        with open(map_path, "w", encoding="utf-8") as fh:
            fh.write(dump_yaml(map_doc))
        n_maps += 1
        domain_profile_dir = os.path.join(profile_dir, domain)
        os.makedirs(domain_profile_dir, exist_ok=True)
        for entry in entries:
            profile = build_profile(domain, entry, md_sections.get(entry["key"]), src_root)
            profile_path = os.path.join(domain_profile_dir, f"{entry['key']}.yaml")
            with open(profile_path, "w", encoding="utf-8") as fh:
                fh.write(dump_yaml(profile))
            n_profiles += 1
        print(f"  {domain}: map + {len(entries)} profiles")

    print(f"\nwrote {n_maps} maps and {n_profiles} profiles under {out_root}")


if __name__ == "__main__":
    main()
