#!/usr/bin/env python3
"""
generate_per_domain_usecases.py — one-shot (re-)generator for base_academic's
per-domain usecase set (base_academic-usecase-atomicity-proposal.md's
per-domain split). Regenerates:

  plan/usecase/{4a,4b,4c,4d,5,5a,5b,5c,5d}-*.md   — one doc per (stage, domain)
  script/verify/uc{...}_{domain}.py               — thin wrappers around
                                                      script/verify/_common.py
  the `usecases:` block of script/schema/standard.yaml

A future concrete system with a different domain list re-runs this with
its own STRUCTURAL_DOMAINS/CITE_CONTEXT_DOMAINS to stand up its own copy
of the per-domain file set — same override surface it already has for
templates/rubrics, applied here to the usecase registry.

Run from repo root: python script/schema/generate_per_domain_usecases.py
"""
import re
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent.parent  # base_academic/

STRUCTURAL_DOMAINS = [
    "title-and-metadata", "abstract", "introduction", "related-work",
    "problem-definition", "methodology", "experimental-setup", "results",
    "discussion", "limitations", "conclusion", "references",
]
GENERATED_DOMAINS = [d for d in STRUCTURAL_DOMAINS if d != "references"]
CITE_CONTEXT_DOMAINS = {"related-work", "introduction", "discussion"}


def snake(domain):
    return domain.replace("-", "_")


def write(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


VERIFY_TEMPLATE = '''"""Verify script for {usecase_name} — generated by
script/schema/generate_per_domain_usecases.py, do not hand-edit; edit that
generator and re-run instead."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import verify_main

if __name__ == "__main__":
    verify_main("{usecase_name}")
'''


def gen_verify(filename, usecase_name):
    write(BASE / "script" / "verify" / filename,
          VERIFY_TEMPLATE.format(usecase_name=usecase_name))


DOC_TEMPLATE = """# Use-case {label} — {title}

**Depends on**: {depends_on}

**Script**: {script}

**Inputs**: {inputs}

**Action**: {action}

**Completion criteria** (checked by verify script):
- {completion}

**Verify script**: `script/verify/{verify_file} --paper-id <id>`

**Rule**: {rule}
"""


def gen_doc(filename, **kwargs):
    write(BASE / "plan" / "usecase" / filename, DOC_TEMPLATE.format(**kwargs))


def main():
    usecases_yaml = []  # (name, description) pairs, in emission order

    # --- 4a: generate-section-draft-{domain} ---
    for d in GENERATED_DOMAINS:
        name = f"generate-section-draft-{d}"
        verify_file = f"uc4a_generate_{snake(d)}.py"
        gen_verify(verify_file, name)
        gen_doc(f"4a-generate-{d}.md",
                label=f"4a-{d}", title=f"Generate Section Draft — {d}",
                depends_on=("`novelty-analysis` + `gap-analysis` + `mathematics-analysis` (3a) "
                            "+ `diagram-architecture-analysis` (3b)"),
                script=(f"`gather-domain-evidence` (mode=generate, domain={d}) -> "
                        f"`generate-section` (prompt, template=`templates/generation/markdown/{d}.md`) "
                        "-> `persist-section-draft` (stage=generate)"),
                inputs=(f"Repo documentation, analysis docs, novelty/gap findings scoped to `{d}`, "
                        f"`templates/generation/markdown/{d}.md`"),
                action=(f"Generate the `{d}` section's initial deep content — structure, argument, "
                        "claims grounded in evidence. In-repo grounding markers only "
                        "(external literature -> 4b, math/table weaving -> 4c)."),
                completion=(f"`SELECT COUNT(*) FROM academic_narratives WHERE domain_id="
                            f"(SELECT id FROM academic_domains WHERE key='{d}') AND stage='generate'` >= 1"),
                verify_file=verify_file,
                rule="Runs after 3a+3b have results. Independently re-runnable — a re-run of this domain does not touch any other domain's draft.")
        usecases_yaml.append((name, f"generate {d}'s initial deep content from its template"))

    # --- 4b: section-citations-{domain} (11) + section-citations-references (fan-in) ---
    for d in GENERATED_DOMAINS:
        name = f"section-citations-{d}"
        verify_file = f"uc4b_cite_{snake(d)}.py"
        gen_verify(verify_file, name)
        cite_ctx = d in CITE_CONTEXT_DOMAINS
        extra_script = (" + `literature-review-pass` (prompt, external lit search) "
                         "-> `persist-section-citations` (source_kind=literature) "
                         "-> `persist-section-draft` (stage=cite)") if cite_ctx else ""
        gen_doc(f"4b-cite-{d}.md",
                label=f"4b-{d}", title=f"Section Citations — {d}",
                depends_on=f"`generate-section-draft-{d}` (4a)",
                script=(f"`gather-domain-evidence` (mode=citation, domain={d}) -> "
                        f"`persist-section-citations` (source_kind=in-repo){extra_script}"),
                inputs=f"`{d}`'s stage='generate' draft" + (" + external literature corpus" if cite_ctx else ""),
                action=(f"Extract in-repo grounding markers already present in `{d}`'s draft, persist them "
                        "as real, queryable citations (previously silently dropped)."
                        + (f" `{d}` is also a `CITE_CONTEXT_DOMAINS` member — runs an external-literature "
                           "search pass on top of the in-repo citations." if cite_ctx else "")),
                completion=(f"`SELECT COUNT(*) FROM academic_section_citations WHERE domain_id="
                            f"(SELECT id FROM academic_domains WHERE key='{d}')` >= 1"),
                verify_file=verify_file,
                rule="Runs after this domain's own 4a. Independent of every other domain's citation usecase.")
        usecases_yaml.append((name, f"attach real citations to {d}'s draft" + (" (+ external literature)" if cite_ctx else "")))

    ref_name = "section-citations-references"
    ref_verify = "uc4b_collate_references.py"
    gen_verify(ref_verify, ref_name)
    gen_doc("4b-collate-references.md",
            label="4b-references", title="Section Citations — references (collation, fan-in)",
            depends_on="all 11 `section-citations-{domain}` usecases (every non-references domain)",
            script="`collate-references` (det, single step — dedupes + formats every collected citation) -> writes references' stage='cite' narrative directly",
            inputs="Every domain's `academic_section_citations` rows",
            action=("Build the `references` domain's first-ever draft from what the other 11 domains "
                    "actually cited — `references` has no stage='generate' row (4a skips it), its "
                    "content is strictly a function of this collation."),
            completion="`SELECT COUNT(*) FROM academic_narratives WHERE domain_id=(SELECT id FROM academic_domains WHERE key='references') AND stage='cite'` >= 1",
            verify_file=ref_verify,
            rule="Fan-in — this usecase's own script calls usecase_status() for each of the 11 upstream section-citations-* usecases and hard-fails, listing which are still outstanding, rather than collating a partial citation list.")
    usecases_yaml.append((ref_name, "collate all domains' citations into the references domain's first draft"))

    # --- 4c: section-supplementary-content-{domain} (12) ---
    for d in STRUCTURAL_DOMAINS:
        name = f"section-supplementary-content-{d}"
        verify_file = f"uc4c_enrich_{snake(d)}.py"
        gen_verify(verify_file, name)
        gen_doc(f"4c-enrich-{d}.md",
                label=f"4c-{d}", title=f"Section Supplementary Content — {d}",
                depends_on=(f"`section-citations-{d}`" if d != "references" else "`section-citations-references`")
                           + " + `mathematics-analysis` (3a) + `diagram-architecture-analysis` (3b)",
                script=(f"`gather-domain-evidence` (mode=enrich, domain={d}) -> "
                        "`section-enrichment` (prompt) -> `persist-section-draft` (stage=enrich)"),
                inputs=f"`{d}`'s stage='cite' draft, 3a/3b findings relevant to `{d}` (no-op pass-through if none relevant)",
                action=(f"Weave in equations, tables, and diagram references into `{d}` where its content "
                        "actually calls for them. A no-op for domains with nothing relevant still produces "
                        "a stage='enrich' row (uniform completion predicate)."),
                completion=(f"`SELECT COUNT(*) FROM academic_narratives WHERE domain_id="
                            f"(SELECT id FROM academic_domains WHERE key='{d}') AND stage='enrich'` >= 1"),
                verify_file=verify_file,
                rule="Runs after this domain's own 4b. Independently re-runnable.")
        usecases_yaml.append((name, f"weave math/tables/diagrams into {d} where relevant"))

    # --- 4d: section-budget-fit-{domain} (12) + section-budget-fit-total (fan-in) ---
    for d in STRUCTURAL_DOMAINS:
        name = f"section-budget-fit-{d}"
        verify_file = f"uc4d_budget_{snake(d)}.py"
        gen_verify(verify_file, name)
        gen_doc(f"4d-budget-{d}.md",
                label=f"4d-{d}", title=f"Section Budget Fit — {d}",
                depends_on=f"`section-supplementary-content-{d}` (4c)",
                script=(f"`check-word-budget` (det, domain={d}) -> `fit-to-budget` (prompt, conditional — "
                        "only if out of range) -> `persist-section-draft` (stage=budget-fit)"),
                inputs=f"`{d}`'s stage='enrich' draft, `calculation/deterministic/{d}.yaml`'s word_count_in_range config",
                action=(f"Fit `{d}` into its configured min/max word range. In-range drafts pass through "
                        "unchanged (still get a stage='budget-fit' row); out-of-range drafts get trimmed "
                        "or expanded toward the target."),
                completion=(f"`SELECT COUNT(*) FROM academic_narratives WHERE domain_id="
                            f"(SELECT id FROM academic_domains WHERE key='{d}') AND stage='budget-fit'` >= 1"),
                verify_file=verify_file,
                rule="Runs after this domain's own 4c. Does NOT check the whole-paper total — see section-budget-fit-total.")
        usecases_yaml.append((name, f"fit {d} into its own configured word budget"))

    total_name = "section-budget-fit-total"
    total_verify = "uc4d_budget_total.py"
    gen_verify(total_verify, total_name)
    gen_doc("4d-budget-total.md",
            label="4d-total", title="Section Budget Fit — whole-paper total (fan-in)",
            depends_on="all 12 `section-budget-fit-{domain}` usecases",
            script="No script of its own — reads the sum of every domain's stage='budget-fit' word count against `calculation/summary/paper-budget.yaml`",
            inputs="Every domain's stage='budget-fit' narrative + `calculation/summary/paper-budget.yaml`",
            action="Check that 12 independently-in-range sections still sum to a whole-paper total within the venue's page/word limit.",
            completion="`SUM(word_count)` across all stage='budget-fit' narratives is within `calculation/summary/paper-budget.yaml`'s `total_word_count` range",
            verify_file=total_verify,
            rule="Fan-in, whole-paper concern — gates deterministic-audit-* the same way every other domain-level 4d usecase does.")
    usecases_yaml.append((total_name, "check whole-paper word count against the venue's total budget"))

    # --- 5: deterministic-audit-{domain} (12) ---
    for d in STRUCTURAL_DOMAINS:
        name = f"deterministic-audit-{d}"
        verify_file = f"uc5_audit_det_{snake(d)}.py"
        gen_verify(verify_file, name)
        gen_doc(f"5-audit-det-{d}.md",
                label=f"5-{d}", title=f"Deterministic Audit — {d}",
                depends_on=f"`section-budget-fit-{d}` (4d) + `section-budget-fit-total`",
                script=f"`deterministic-audit` (det, domain={d})",
                inputs=f"`{d}`'s stage='budget-fit' draft, `calculation/deterministic/{d}.yaml` rule file",
                action=f"Run `{d}`'s mechanical checks (word count, citation markers, no placeholders). Cheap fail-fast before semantic scoring.",
                completion=(f"`SELECT verdict FROM academic_deterministic_findings WHERE domain_id="
                            f"(SELECT id FROM academic_domains WHERE key='{d}') ORDER BY run_number DESC LIMIT 1` = PASS"),
                verify_file=verify_file,
                rule="Re-runnable. PASS gates semantic-audit-{d}.")
        usecases_yaml.append((name, f"run {d}'s deterministic mechanical checks"))

    # --- 5a: semantic-audit-{domain} (12) ---
    for d in STRUCTURAL_DOMAINS:
        name = f"semantic-audit-{d}"
        verify_file = f"uc5a_audit_sem_{snake(d)}.py"
        gen_verify(verify_file, name)
        gen_doc(f"5a-audit-sem-{d}.md",
                label=f"5a-{d}", title=f"Semantic Audit — {d}",
                depends_on=f"`deterministic-audit-{d}` (PASS)",
                script=(f"`gather-domain-evidence` (mode=audit, domain={d}) -> `semantic-audit` (prompt) "
                        "-> `persist-domain-semantic-score` (scope=section-full)"),
                inputs=f"`{d}`'s draft, `calculation/semantic/document/{d}.md` rubric",
                action=f"Score `{d}`'s draft against its rubric.",
                completion=(f"`SELECT COUNT(*) FROM academic_semantic_runs WHERE domain_id="
                            f"(SELECT id FROM academic_domains WHERE key='{d}') AND scope='section-full'` >= 1"),
                verify_file=verify_file,
                rule="Accumulates indefinitely — re-running adds run_numbers, never overwrites. Only runs if deterministic-audit-{d} PASS.")
        usecases_yaml.append((name, f"score {d} against its rubric"))

    # --- 5b: plagiarism-forensic-audit-{domain} (12) ---
    for d in STRUCTURAL_DOMAINS:
        name = f"plagiarism-forensic-audit-{d}"
        verify_file = f"uc5b_plagiarism_{snake(d)}.py"
        gen_verify(verify_file, name)
        gen_doc(f"5b-plagiarism-{d}.md",
                label=f"5b-{d}", title=f"Plagiarism Forensic Audit — {d}",
                depends_on=f"`section-budget-fit-{d}` (4d) — same relationship as the pre-split pipeline, scoped to one domain",
                script=("`gather-plagiarism-context` -> `deterministic-fingerprint-check` (det) -> "
                        "`plagiarism-fingerprint-audit` (prompt) -> `targeted-rewrite` (prompt, conditional) "
                        "-> `persist-plagiarism-findings`"),
                inputs=f"`{d}`'s draft, banned phrases, reference corpus",
                action=f"Deterministic pre-screen + semantic forensic audit + conditional targeted rewrite for `{d}`.",
                completion=(f"`SELECT verdict FROM academic_plagiarism_findings WHERE domain_id="
                            f"(SELECT id FROM academic_domains WHERE key='{d}') AND pass_type='forensic' "
                            "ORDER BY run_number DESC LIMIT 1` exists"),
                verify_file=verify_file,
                rule="Independently re-runnable per domain.")
        usecases_yaml.append((name, f"plagiarism/fingerprint check {d}"))

    # --- 5c: humanize-deterministic-{domain} (12) ---
    for d in STRUCTURAL_DOMAINS:
        name = f"humanize-deterministic-{d}"
        verify_file = f"uc5c_humanize_det_{snake(d)}.py"
        gen_verify(verify_file, name)
        gen_doc(f"5c-humanize-det-{d}.md",
                label=f"5c-{d}", title=f"Humanize Deterministic — {d}",
                depends_on=f"`plagiarism-forensic-audit-{d}` (FAIL after targeted rewrite)",
                script="`gather-humanize-context` -> `nlp-fingerprint-fix` (det — sentence-length variance, parallel-structure breaking)",
                inputs=f"`{d}`'s draft + flagged spans, if `{d}` is flagged (else a no-op)",
                action=f"Mechanical AI-fingerprint fixes for `{d}` a library can do reliably — no-op if `{d}` was never flagged.",
                completion=f"If flagged: `SELECT COUNT(*) FROM academic_humanize_passes WHERE domain_id=(SELECT id FROM academic_domains WHERE key='{d}') AND pass_kind='deterministic'` >= 1. If never flagged: trivially complete.",
                verify_file=verify_file,
                rule="Only meaningfully runs for domains still flagged after plagiarism-forensic-audit-{d}; a no-op elsewhere.")
        usecases_yaml.append((name, f"NLP mechanical fingerprint fix for {d} (no-op if not flagged)"))

    # --- 5d: humanize-semantic-{domain} (12) ---
    for d in STRUCTURAL_DOMAINS:
        name = f"humanize-semantic-{d}"
        verify_file = f"uc5d_humanize_sem_{snake(d)}.py"
        gen_verify(verify_file, name)
        gen_doc(f"5d-humanize-sem-{d}.md",
                label=f"5d-{d}", title=f"Humanize Semantic — {d}",
                depends_on=f"`humanize-deterministic-{d}` (still flagged after deterministic pass)",
                script="`gather-humanize-context` -> `humanize-section` (prompt, Layers 2-3 only) -> `persist-humanize-pass` (pass_kind=semantic)",
                inputs=f"`{d}`'s deterministic-fixed draft, if `{d}` is still flagged (else a no-op)",
                action=f"LLM rewrite (technical DNA injection + voice restoration) for `{d}` — no-op if `{d}` was resolved by the deterministic pass alone or never flagged.",
                completion=f"If still flagged: `SELECT COUNT(*) FROM academic_humanize_passes WHERE domain_id=(SELECT id FROM academic_domains WHERE key='{d}') AND pass_kind='semantic'` >= 1. Otherwise trivially complete.",
                verify_file=verify_file,
                rule="Gates document-narrative-polish (4e) together with every other domain's 5c/5d.")
        usecases_yaml.append((name, f"LLM humanize rewrite for {d} (no-op if resolved earlier)"))

    # --- Splice standard.yaml's usecases: block ---
    std_path = BASE / "script" / "schema" / "standard.yaml"
    std = std_path.read_text(encoding="utf-8")
    marker = "\nusecases:\n"
    idx = std.index(marker)
    head = std[:idx + len(marker)]

    kept = """  - name: schema-init
    description: "create base_academic's own tables before anything else writes to them"
    steps:
      - order: 1
        kind: deterministic
        description: "Create 21 academic_* tables, seed domains and templates"
        script: init-schema

  - name: classify-repo
    description: "entry router — scan repo for documentation, classify into NO_DOCS / HAS_DOCS"
    steps:
      - order: 1
        kind: deterministic
        description: "Scan repo for author-supplied documentation; persist classification"
        script: classify-repo

  - name: novelty-analysis
    description: "identify what's novel, sourced from the repo's actual documentation"
    steps: []
    # Per-module + cross-module triads expanded at runtime by expand_triads()

  - name: gap-analysis
    description: "identify gaps, sourced from the repo's actual documentation"
    steps: []
    # Per-module + cross-module triads expanded at runtime by expand_triads()

  - name: mathematics-analysis
    description: "derive mathematical formalization from documentation"
    steps: []
    # Per-module + cross-module triads expanded at runtime

  - name: diagram-architecture-analysis
    description: "derive mermaid diagrams and architecture analysis from documentation"
    steps: []
    # Per-module + cross-module triads expanded at runtime
"""

    per_domain_block = ""
    for name, desc in usecases_yaml:
        per_domain_block += f"""
  - name: {name}
    description: "{desc}"
    steps: []
    # Per-domain usecase — base_academic-usecase-atomicity-proposal.md"""
    per_domain_block += "\n"

    tail = """
  - name: document-narrative-polish
    description: "whole-document 3-pass polish: structure, narrative style, content detail"
    steps: []
    # 3 sequential sub-steps expanded at runtime

  - name: cross-section-semantic-audit
    description: "consistency review across all sections for terminology, claims, and narrative coherence"
    steps: []
    # Single-step expanded at runtime

  - name: document-semantic-audit
    description: "whole-document holistic review as one continuous document"
    steps: []
    # Single-step expanded at runtime

  - name: calculate
    description: "calculate final scores from semantic + deterministic buckets + cross-section/document coherence, track trend"
    steps: []
    # Single-step, expanded at runtime when calculate.py is built

  - name: render-charts
    description: "generate chart images from score/audit data (domain-score-bar, heatmap, cross-section, document)"
    steps: []
    # Single-step, expanded at runtime

  - name: render-audit-report
    description: "score-driven audit report with charts and trend visualization"
    steps: []
    # Depends on render-charts; single-step expanded at runtime

  - name: render-paper
    description: "assemble paper from domain drafts, render through HTML/PDF/DOCX"
    steps: []
    # Depends on document-semantic-audit; single-step expanded at runtime
"""

    new_std = head + kept + per_domain_block + tail
    std_path.write_text(new_std, encoding="utf-8")

    # --- Delete the 9 stale combined docs + verify scripts this replaces ---
    stale_docs = [
        "4a-generate-section-draft.md", "4b-section-citations.md",
        "4c-section-supplementary-content.md", "4d-section-budget-fit.md",
        "5-deterministic-audit.md", "5a-semantic-audit.md",
        "5b-plagiarism-forensic-audit.md", "5c-humanize-deterministic.md",
        "5d-humanize-semantic.md",
    ]
    stale_verify = [
        "uc4a_generate_section.py", "uc4b_section_citations.py",
        "uc4c_section_enrichment.py", "uc4d_section_budget_fit.py",
        "uc5_det_audit.py", "uc5a_semantic_audit.py", "uc5b_plagiarism.py",
        "uc5c_humanize_deterministic.py", "uc5d_humanize_semantic.py",
    ]
    for f in stale_docs:
        p = BASE / "plan" / "usecase" / f
        if p.exists():
            p.unlink()
    for f in stale_verify:
        p = BASE / "script" / "verify" / f
        if p.exists():
            p.unlink()

    print(f"generated {len(usecases_yaml)} per-domain usecases")
    print(f"standard.yaml usecases: block rewritten ({std_path})")
    print(f"deleted {len(stale_docs)} stale docs + {len(stale_verify)} stale verify scripts")


if __name__ == "__main__":
    main()
