"""generate_templates.py — Generate 144 per-domain report templates
(12 domains × 6 kinds × 2 formats) for base_academic.

Also migrates legacy shared templates:
  - DELETE  markdown/deterministic.md, html/deterministic.html
  - DELETE  markdown/semantic.md, html/semantic.html
  - RENAME  markdown/summary.md -> markdown/whole-paper-summary.md
  - RENAME  html/summary.html  -> html/whole-paper-summary.html
  - Pipeline-progress.* left untouched.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "templates" / "report"

DOMAINS = [
    "title-and-metadata", "abstract", "introduction", "related-work",
    "problem-definition", "methodology", "experimental-setup", "results",
    "discussion", "limitations", "conclusion", "references",
]
DISPLAY_NAMES = {
    "title-and-metadata": "Title & Metadata",
    "abstract": "Abstract",
    "introduction": "Introduction",
    "related-work": "Related Work",
    "problem-definition": "Problem Definition",
    "methodology": "Methodology",
    "experimental-setup": "Experimental Setup",
    "results": "Results",
    "discussion": "Discussion",
    "limitations": "Limitations",
    "conclusion": "Conclusion",
    "references": "References",
}

CSS = (
    "body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; "
    "max-width: 1100px; margin: 0 auto; padding: 2rem; color: #333; }\n"
    "h1 { border-bottom: 2px solid #2c3e50; padding-bottom: 0.5rem; }\n"
    "h2 { color: #2c3e50; margin-top: 2rem; }\n"
    "table { width: 100%; border-collapse: collapse; margin: 1rem 0; }\n"
    "th, td { padding: 0.6rem 1rem; border: 1px solid #ddd; text-align: left; }\n"
    "th { background: #f8f9fa; font-weight: 600; }\n"
    "tr:nth-child(even) { background: #fafafa; }\n"
    ".pass { color: #27ae60; font-weight: bold; }\n"
    ".fail { color: #e74c3c; font-weight: bold; }\n"
    ".na { color: #95a5a6; }\n"
    ".meta { color: #7f8c8d; font-size: 0.9rem; }"
)


def html_boilerplate(title, body):
    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '    <meta charset="UTF-8">\n'
        '    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
        f"    <title>{title}</title>\n"
        "    <style>\n"
        + "\n".join(f"        {line}" for line in CSS.split("\n"))
        + "\n    </style>\n"
        "</head>\n"
        "<body>\n"
        + "\n".join(f"    {line}" for line in body.split("\n"))
        + "\n</body>\n"
        "</html>\n"
    )


# ---------------------------------------------------------------------------
# Markdown templates (one per kind)
# ---------------------------------------------------------------------------

def md_deterministic(dn):
    return f"""# {dn} — Deterministic Audit

**Generated:** {{{{ timestamp }}}}
**Paper ID:** {{{{ paper_id }}}}

---

## Check Breakdown

| Check | Status | Detail |
|-------|--------|--------|
{{{{#checks}}}}
| {{{{ check_id }}}} | {{{{ status }}}} | {{{{ detail }}}} |
{{{{/checks}}}}

## Verdict

**Result:** {{{{ verdict }}}}

---

*Report generated by base_academic deterministic audit.*
"""


def md_semantic_full(dn):
    return f"""# {dn} — Semantic Audit (Full)

**Generated:** {{{{ timestamp }}}}
**Paper ID:** {{{{ paper_id }}}}

---

## Model Scores

| Model | Score | Agreement |
|-------|-------|-----------|
{{{{#models}}}}
| {{{{ model }}}} | {{{{ score }}}} | {{{{ agreement }}}} |
{{{{/models}}}}

## Ensemble

- **Mean Score:** {{{{ mean_score }}}}
- **Model Agreement:** {{{{ agreement_level }}}}
- **Standard Deviation:** {{{{ stdev_score }}}}

## Dimension Scores

| Dimension | Score | Evidence |
|-----------|-------|----------|
{{{{#dimensions}}}}
| {{{{ dimension_key }}}} | {{{{ score }}}} | {{{{ evidence }}}} |
{{{{/dimensions}}}}

## Findings

{{{{#strengths}}}}
- **Strength:** {{{{ . }}}}
{{{{/strengths}}}}
{{{{#weaknesses}}}}
- **Weakness:** {{{{ . }}}}
{{{{/weaknesses}}}}
{{{{#recommendations}}}}
- **Recommendation:** {{{{ . }}}}
{{{{/recommendations}}}}

---

*Report generated by base_academic semantic audit.*
"""


def md_semantic_part(dn):
    return f"""# {dn} — Semantic Audit (Part Scores)

**Generated:** {{{{ timestamp }}}}
**Paper ID:** {{{{ paper_id }}}}

---

## Part Scores

| Part | Score | Verdict |
|------|-------|---------|
{{{{#parts}}}}
| {{{{ part_kind }}}} | {{{{ score }}}} | {{{{ verdict }}}} |
{{{{/parts}}}}

## Findings by Part

{{{{#parts}}}}
### {{{{ part_kind }}}}
{{{{#findings}}}}
- **{{{{ concern }}}}**: {{{{ detail }}}} (severity: {{{{ severity }}}})
{{{{/findings}}}}
{{{{/parts}}}}

---

*Report generated by base_academic semantic audit.*
"""


def md_plagiarism(dn):
    return f"""# {dn} — Plagiarism Forensic Audit

**Generated:** {{{{ timestamp }}}}
**Paper ID:** {{{{ paper_id }}}}

---

## Verdict

**Result:** {{{{ verdict }}}}

## Findings

{{{{#findings}}}}
- **{{{{ check_id }}}}**: {{{{ detail }}}} (severity: {{{{ severity }}}})
{{{{/findings}}}}

{{{{^findings}}}}
No findings recorded.
{{{{/findings}}}}

---

*Report generated by base_academic plagiarism audit.*
"""


def md_humanize(dn):
    return f"""# {dn} — Humanize Passes

**Generated:** {{{{ timestamp }}}}
**Paper ID:** {{{{ paper_id }}}}

---

## Deterministic Pass

- **Iteration:** {{{{ det_iteration }}}}
- **Risk Flags:** {{{{ det_risk_flags }}}}

## Semantic Pass

- **Iteration:** {{{{ sem_iteration }}}}
- **Risk Flags:** {{{{ sem_risk_flags }}}}

## Risk Flags Detail

{{{{#risk_flag_list}}}}
- {{{{ . }}}}
{{{{/risk_flag_list}}}}

{{{{^risk_flag_list}}}}
No risk flags.
{{{{/risk_flag_list}}}}

---

*Report generated by base_academic humanize audit.*
"""


def md_summary(dn):
    return f"""# {dn} — Domain Summary

**Generated:** {{{{ timestamp }}}}
**Paper ID:** {{{{ paper_id }}}}

---

## Aggregation Score

- **Final Score:** {{{{ final_score }}}}
- **Score Band:** {{{{ score_band }}}}

## Component Scores

- **Deterministic:** {{{{ deterministic_score }}}}
- **Semantic (blended):** {{{{ semantic_score }}}}

## Score History

- **Trend:** {{{{ trend }}}}

---

*Report generated by base_academic audit pipeline.*
"""


# ---------------------------------------------------------------------------
# HTML templates (one per kind)
# ---------------------------------------------------------------------------

def html_deterministic(dn):
    body = (
        f'<h1>{dn} — Deterministic Audit</h1>\n'
        '    <p class="meta">Generated: {{{{ timestamp }}}} | Paper ID: {{{{ paper_id }}}}</p>\n'
        "\n"
        "    <h2>Check Breakdown</h2>\n"
        "    <table>\n"
        "        <thead>\n"
        "            <tr><th>Check</th><th>Status</th><th>Detail</th></tr>\n"
        "        </thead>\n"
        "        <tbody>\n"
        "            {{{{#checks}}}}\n"
        "            <tr>\n"
        "                <td>{{{{ check_id }}}}</td>\n"
        '                <td class="{{{{ status_class }}}}">{{{{ status }}}}</td>\n'
        "                <td>{{{{ detail }}}}</td>\n"
        "            </tr>\n"
        "            {{{{/checks}}}}\n"
        "        </tbody>\n"
        "    </table>\n"
        "\n"
        "    <h2>Verdict</h2>\n"
        "    <p><strong>Result:</strong> {{{{ verdict }}}}</p>\n"
        "\n"
        "    <hr>\n"
        '    <p class="meta">Report generated by base_academic deterministic audit.</p>\n'
    )
    return html_boilerplate(f"{dn} — Deterministic Audit", body)


def html_semantic_full(dn):
    body = (
        f'<h1>{dn} — Semantic Audit (Full)</h1>\n'
        '    <p class="meta">Generated: {{{{ timestamp }}}} | Paper ID: {{{{ paper_id }}}}</p>\n'
        "\n"
        "    <h2>Model Scores</h2>\n"
        "    <table>\n"
        "        <thead>\n"
        "            <tr><th>Model</th><th>Score</th><th>Agreement</th></tr>\n"
        "        </thead>\n"
        "        <tbody>\n"
        "            {{{{#models}}}}\n"
        "            <tr>\n"
        "                <td>{{{{ model }}}}</td>\n"
        "                <td>{{{{ score }}}}</td>\n"
        "                <td>{{{{ agreement }}}}</td>\n"
        "            </tr>\n"
        "            {{{{/models}}}}\n"
        "        </tbody>\n"
        "    </table>\n"
        "\n"
        "    <h2>Ensemble</h2>\n"
        "    <ul>\n"
        "        <li><strong>Mean Score:</strong> {{{{ mean_score }}}}</li>\n"
        "        <li><strong>Model Agreement:</strong> {{{{ agreement_level }}}}</li>\n"
        "        <li><strong>Standard Deviation:</strong> {{{{ stdev_score }}}}</li>\n"
        "    </ul>\n"
        "\n"
        "    <h2>Dimension Scores</h2>\n"
        "    <table>\n"
        "        <thead>\n"
        "            <tr><th>Dimension</th><th>Score</th><th>Evidence</th></tr>\n"
        "        </thead>\n"
        "        <tbody>\n"
        "            {{{{#dimensions}}}}\n"
        "            <tr>\n"
        "                <td>{{{{ dimension_key }}}}</td>\n"
        "                <td>{{{{ score }}}}</td>\n"
        "                <td>{{{{ evidence }}}}</td>\n"
        "            </tr>\n"
        "            {{{{/dimensions}}}}\n"
        "        </tbody>\n"
        "    </table>\n"
        "\n"
        "    <h2>Findings</h2>\n"
        "    <h3>Strengths</h3>\n"
        "    <ul>\n"
        "        {{{{#strengths}}}}\n"
        '        <li><strong>Strength:</strong> {{{{ . }}}}</li>\n'
        "        {{{{/strengths}}}}\n"
        "    </ul>\n"
        "    <h3>Weaknesses</h3>\n"
        "    <ul>\n"
        "        {{{{#weaknesses}}}}\n"
        '        <li><strong>Weakness:</strong> {{{{ . }}}}</li>\n'
        "        {{{{/weaknesses}}}}\n"
        "    </ul>\n"
        "    <h3>Recommendations</h3>\n"
        "    <ul>\n"
        "        {{{{#recommendations}}}}\n"
        '        <li><strong>Recommendation:</strong> {{{{ . }}}}</li>\n'
        "        {{{{/recommendations}}}}\n"
        "    </ul>\n"
        "\n"
        "    <hr>\n"
        '    <p class="meta">Report generated by base_academic semantic audit.</p>\n'
    )
    return html_boilerplate(f"{dn} — Semantic Audit (Full)", body)


def html_semantic_part(dn):
    body = (
        f'<h1>{dn} — Semantic Audit (Part Scores)</h1>\n'
        '    <p class="meta">Generated: {{{{ timestamp }}}} | Paper ID: {{{{ paper_id }}}}</p>\n'
        "\n"
        "    <h2>Part Scores</h2>\n"
        "    <table>\n"
        "        <thead>\n"
        "            <tr><th>Part</th><th>Score</th><th>Verdict</th></tr>\n"
        "        </thead>\n"
        "        <tbody>\n"
        "            {{{{#parts}}}}\n"
        "            <tr>\n"
        "                <td>{{{{ part_kind }}}}</td>\n"
        "                <td>{{{{ score }}}}</td>\n"
        "                <td>{{{{ verdict }}}}</td>\n"
        "            </tr>\n"
        "            {{{{/parts}}}}\n"
        "        </tbody>\n"
        "    </table>\n"
        "\n"
        "    <h2>Findings by Part</h2>\n"
        "    {{{{#parts}}}}\n"
        "    <h3>{{{{ part_kind }}}}</h3>\n"
        "    <ul>\n"
        "        {{{{#findings}}}}\n"
        '        <li><strong>{{{{ concern }}}}</strong>: {{{{ detail }}}} (severity: {{{{ severity }}}})</li>\n'
        "        {{{{/findings}}}}\n"
        "    </ul>\n"
        "    {{{{/parts}}}}\n"
        "\n"
        "    <hr>\n"
        '    <p class="meta">Report generated by base_academic semantic audit.</p>\n'
    )
    return html_boilerplate(f"{dn} — Semantic Audit (Part Scores)", body)


def html_plagiarism(dn):
    body = (
        f'<h1>{dn} — Plagiarism Forensic Audit</h1>\n'
        '    <p class="meta">Generated: {{{{ timestamp }}}} | Paper ID: {{{{ paper_id }}}}</p>\n'
        "\n"
        "    <h2>Verdict</h2>\n"
        "    <p><strong>Result:</strong> {{{{ verdict }}}}</p>\n"
        "\n"
        "    <h2>Findings</h2>\n"
        "    <ul>\n"
        "        {{{{#findings}}}}\n"
        '        <li><strong>{{{{ check_id }}}}</strong>: {{{{ detail }}}} (severity: {{{{ severity }}}})</li>\n'
        "        {{{{/findings}}}}\n"
        "    </ul>\n"
        "\n"
        "    {{{{^findings}}}}\n"
        "    <p>No findings recorded.</p>\n"
        "    {{{{/findings}}}}\n"
        "\n"
        "    <hr>\n"
        '    <p class="meta">Report generated by base_academic plagiarism audit.</p>\n'
    )
    return html_boilerplate(f"{dn} — Plagiarism Forensic Audit", body)


def html_humanize(dn):
    body = (
        f'<h1>{dn} — Humanize Passes</h1>\n'
        '    <p class="meta">Generated: {{{{ timestamp }}}} | Paper ID: {{{{ paper_id }}}}</p>\n'
        "\n"
        "    <h2>Deterministic Pass</h2>\n"
        "    <ul>\n"
        "        <li><strong>Iteration:</strong> {{{{ det_iteration }}}}</li>\n"
        "        <li><strong>Risk Flags:</strong> {{{{ det_risk_flags }}}}</li>\n"
        "    </ul>\n"
        "\n"
        "    <h2>Semantic Pass</h2>\n"
        "    <ul>\n"
        "        <li><strong>Iteration:</strong> {{{{ sem_iteration }}}}</li>\n"
        "        <li><strong>Risk Flags:</strong> {{{{ sem_risk_flags }}}}</li>\n"
        "    </ul>\n"
        "\n"
        "    <h2>Risk Flags Detail</h2>\n"
        "    <ul>\n"
        "        {{{{#risk_flag_list}}}}\n"
        "        <li>{{{{ . }}}}</li>\n"
        "        {{{{/risk_flag_list}}}}\n"
        "    </ul>\n"
        "\n"
        "    {{{{^risk_flag_list}}}}\n"
        "    <p>No risk flags.</p>\n"
        "    {{{{/risk_flag_list}}}}\n"
        "\n"
        "    <hr>\n"
        '    <p class="meta">Report generated by base_academic humanize audit.</p>\n'
    )
    return html_boilerplate(f"{dn} — Humanize Passes", body)


def html_summary(dn):
    body = (
        f'<h1>{dn} — Domain Summary</h1>\n'
        '    <p class="meta">Generated: {{{{ timestamp }}}} | Paper ID: {{{{ paper_id }}}}</p>\n'
        "\n"
        "    <h2>Aggregation Score</h2>\n"
        "    <ul>\n"
        "        <li><strong>Final Score:</strong> {{{{ final_score }}}}</li>\n"
        "        <li><strong>Score Band:</strong> {{{{ score_band }}}}</li>\n"
        "    </ul>\n"
        "\n"
        "    <h2>Component Scores</h2>\n"
        "    <ul>\n"
        "        <li><strong>Deterministic:</strong> {{{{ deterministic_score }}}}</li>\n"
        "        <li><strong>Semantic (blended):</strong> {{{{ semantic_score }}}}</li>\n"
        "    </ul>\n"
        "\n"
        "    <h2>Score History</h2>\n"
        "    <p><strong>Trend:</strong> {{{{ trend }}}}</p>\n"
        "\n"
        "    <hr>\n"
        '    <p class="meta">Report generated by base_academic audit pipeline.</p>\n'
    )
    return html_boilerplate(f"{dn} — Domain Summary", body)


# ---------------------------------------------------------------------------
# Template registry
# ---------------------------------------------------------------------------

MARKDOWN_BUILDERS = {
    "deterministic":   md_deterministic,
    "semantic-full":   md_semantic_full,
    "semantic-part":   md_semantic_part,
    "plagiarism":      md_plagiarism,
    "humanize":        md_humanize,
    "summary":         md_summary,
}

HTML_BUILDERS = {
    "deterministic":   html_deterministic,
    "semantic-full":   html_semantic_full,
    "semantic-part":   html_semantic_part,
    "plagiarism":      html_plagiarism,
    "humanize":        html_humanize,
    "summary":         html_summary,
}


# ---------------------------------------------------------------------------
# Legacy template migration
# ---------------------------------------------------------------------------

def migrate_legacy_templates():
    """Rename summary -> whole-paper-summary; delete deterministic & semantic shared."""
    md_dir = OUTPUT / "markdown"
    html_dir = OUTPUT / "html"

    # Rename summary -> whole-paper-summary
    for old_name, new_name in [
        ("summary.md", "whole-paper-summary.md"),
        ("summary.html", "whole-paper-summary.html"),
    ]:
        old = md_dir / old_name if old_name.endswith(".md") else html_dir / old_name
        new = md_dir / new_name if new_name.endswith(".md") else html_dir / new_name
        if old.exists():
            old.rename(new)
            print(f"  Renamed {old.name} -> {new.name}")

    # Delete obsolete shared templates
    for fname in ["deterministic.md", "semantic.md"]:
        fpath = md_dir / fname
        if fpath.exists():
            fpath.unlink()
            print(f"  Deleted {fpath}")

    for fname in ["deterministic.html", "semantic.html"]:
        fpath = html_dir / fname
        if fpath.exists():
            fpath.unlink()
            print(f"  Deleted {fpath}")


# ---------------------------------------------------------------------------
# Whole-paper-summary patch — append domain aggregation scores table
# ---------------------------------------------------------------------------

def patch_whole_paper_summary():
    """Add 12-domain aggregate scores table to the renamed whole-paper-summary files."""
    md_path = OUTPUT / "markdown" / "whole-paper-summary.md"
    html_path = OUTPUT / "html" / "whole-paper-summary.html"

    if md_path.exists():
        content = md_path.read_text(encoding="utf-8")
        agg_block = (
            "\n## Domain Aggregation Scores\n"
            "\n"
            "| Domain | Final Score | Score Band |\n"
            "|--------|-------------|------------|\n"
            "{{#domain_aggregates}}\n"
            "| {{ domain_key }} | {{ final_score }} | {{ score_band }} |\n"
            "{{/domain_aggregates}}\n"
        )
        # Insert before the final "*Report generated" line
        marker = "*Report generated by base_academic audit pipeline.*"
        if marker in content and "Domain Aggregation Scores" not in content:
            content = content.replace(marker, agg_block.strip() + "\n\n" + marker)
            md_path.write_text(content, encoding="utf-8")
            print("  Patched whole-paper-summary.md with domain aggregation table")

    if html_path.exists():
        content = html_path.read_text(encoding="utf-8")
        agg_block = (
            "\n    <h2>Domain Aggregation Scores</h2>\n"
            "    <table>\n"
            "        <thead>\n"
            "            <tr><th>Domain</th><th>Final Score</th><th>Score Band</th></tr>\n"
            "        </thead>\n"
            "        <tbody>\n"
            "            {{#domain_aggregates}}\n"
            "            <tr>\n"
            "                <td><strong>{{ domain_key }}</strong></td>\n"
            "                <td>{{ final_score }}</td>\n"
            "                <td>{{ score_band }}</td>\n"
            "            </tr>\n"
            "            {{/domain_aggregates}}\n"
            "        </tbody>\n"
            "    </table>\n"
        )
        marker = '<p class="meta">Report generated by base_academic audit pipeline.</p>'
        if marker in content and "Domain Aggregation Scores" not in content:
            content = content.replace(marker, agg_block.strip() + "\n\n    " + marker)
            html_path.write_text(content, encoding="utf-8")
            print("  Patched whole-paper-summary.html with domain aggregation table")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    count = 0

    print(f"Output base: {OUTPUT}\n")

    # --- Phase 1: generate per-domain templates ---
    print("Generating per-domain report templates...")
    for domain in DOMAINS:
        dn = DISPLAY_NAMES[domain]
        md_dir = OUTPUT / "markdown" / "domain" / domain
        html_dir = OUTPUT / "html" / "domain" / domain
        md_dir.mkdir(parents=True, exist_ok=True)
        html_dir.mkdir(parents=True, exist_ok=True)

        for kind, md_builder in MARKDOWN_BUILDERS.items():
            md_path = md_dir / f"{kind}.md"
            md_path.write_text(md_builder(dn), encoding="utf-8")
            count += 1
            print(f"  {md_path.relative_to(OUTPUT)}")

        for kind, html_builder in HTML_BUILDERS.items():
            html_path = html_dir / f"{kind}.html"
            html_path.write_text(html_builder(dn), encoding="utf-8")
            count += 1
            print(f"  {html_path.relative_to(OUTPUT)}")

    # --- Phase 2: legacy migration ---
    print("\nMigrating legacy shared templates...")
    migrate_legacy_templates()

    # --- Phase 3: patch whole-paper-summary ---
    print("\nPatching whole-paper-summary with domain aggregation table...")
    patch_whole_paper_summary()

    print(f"\nDone. Total files written: {count}")


if __name__ == "__main__":
    main()
