"""Verify script for section-budget-fit-references — generated by
script/schema/generate_per_domain_usecases.py (pcems_2026), do not hand-edit;
edit that generator and re-run instead.

Delegates to _common.py in this same directory."""
import sys
from pathlib import Path

# _common.py lives in this same directory
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import verify_main

if __name__ == "__main__":
    verify_main("section-budget-fit-references")
