"""Verify script for 6-total — generated by
script/schema/generate_per_domain_usecases.py (pcems_2026), do not hand-edit.

Aggregate and render final report: terminal usecase after all
section-domain pipelines complete."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import verify_main

if __name__ == "__main__":
    verify_main("6-total")
